#!/usr/bin/env bash
# scripts/seed-golden-ideas.sh — populates backend/tests/golden/ideas.json
# 50 diverse startup ideas across industries, geographies, and stages.
# Used by the golden regression suite + bench.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

OUT="$REPO_ROOT/backend/tests/golden/ideas.json"
mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<'JSON'
[
  { "id": "g001", "industry": "fintech",        "geo": "US",     "stage": "idea",      "text": "A neobank for freelancers in the US that auto-categorizes 1099 income, sets aside quarterly tax payments to a high-yield account, and files Schedule SE on their behalf each quarter." },
  { "id": "g002", "industry": "healthtech",     "geo": "EU",     "stage": "validated", "text": "An ML-powered diabetic retinopathy screening kiosk for European pharmacies. Patient gets a 90-second eye scan, results sent to their GP within 24h. Reimbursable in DE/FR/NL." },
  { "id": "g003", "industry": "edtech",         "geo": "India",  "stage": "idea",      "text": "An AI tutor for Indian high-schoolers preparing for JEE/NEET that runs entirely offline on a $40 Android device, syncs progress when WiFi appears, and adapts to each student's weak topics." },
  { "id": "g004", "industry": "saas",           "geo": "Global", "stage": "mvp",       "text": "A no-code workflow builder specifically for Stripe — connect Stripe events to Slack, ClickUp, HubSpot, and Notion without ever touching code or webhooks." },
  { "id": "g005", "industry": "ecommerce",      "geo": "LatAm",  "stage": "idea",      "text": "A WhatsApp-first checkout for Latin American Shopify stores — buyers pay via Pix/MercadoPago in chat, no website redirect, sellers get a Shopify-side dashboard." },
  { "id": "g006", "industry": "marketplace",    "geo": "US",     "stage": "validated", "text": "A two-sided marketplace connecting retired engineers with seed-stage startups for paid 1-hour code reviews. Vetted by alma mater verification + GitHub history." },
  { "id": "g007", "industry": "social",         "geo": "US",     "stage": "idea",      "text": "A book club app that pairs strangers reading the same book at the same pace into 4-person Discord-style rooms. Pace enforced by Kindle-progress sync." },
  { "id": "g008", "industry": "ai_ml",          "geo": "Global", "stage": "mvp",       "text": "A platform that lets product managers run user-research interviews with synthetic personas trained on their own customer transcripts. 10x cheaper than actual interviews for pre-validation." },
  { "id": "g009", "industry": "sustainability", "geo": "EU",     "stage": "idea",      "text": "A carbon-accounting SaaS specifically for small EU manufacturers (5-50 employees) preparing for CSRD mandatory reporting in 2026. Pulls from QuickBooks + utility bills." },
  { "id": "g010", "industry": "logistics",      "geo": "Africa", "stage": "idea",      "text": "A last-mile delivery network for Nigerian e-commerce that uses motorcycle owners as 'on-demand fleets' — paid per drop, dispatch via USSD for low-data areas." },
  { "id": "g011", "industry": "entertainment",  "geo": "US",     "stage": "idea",      "text": "A live music app where fans bid on which 3 songs the band plays next at the show. Top 3 bidders get on stage to sing backup. Revenue split with venue + band." },
  { "id": "g012", "industry": "fintech",        "geo": "UK",     "stage": "validated", "text": "An invoice-financing platform for UK creator economy (YouTubers, Substack writers) using brand-deal contracts as collateral. Same-day funding at 4-8% vs 30-90 day waits." },
  { "id": "g013", "industry": "healthtech",     "geo": "US",     "stage": "idea",      "text": "A pelvic-floor PT app for postpartum women, prescribed by OBs and reimbursed by US insurance. Uses phone camera + smart cushion to give real-time form feedback." },
  { "id": "g014", "industry": "edtech",         "geo": "US",     "stage": "mvp",       "text": "A live, peer-led tutoring marketplace where high-school AP students teach younger students for $20/hr. Built for SAT/AP prep. 70% margin to tutor, 20% to platform, 10% scholarship fund." },
  { "id": "g015", "industry": "saas",           "geo": "Global", "stage": "idea",      "text": "A 'pricing room' tool for B2B SaaS founders — pull competitor pricing, customer interview transcripts, and Stripe revenue data, get a recommended price ladder with conviction levels." },
  { "id": "g016", "industry": "ecommerce",      "geo": "US",     "stage": "validated", "text": "A consignment-style storage for parents of toddlers — drop off outgrown clothes, we list and ship to other parents, you take store credit. Zero-inventory secondhand kid retail." },
  { "id": "g017", "industry": "marketplace",    "geo": "US",     "stage": "idea",      "text": "An on-demand network of licensed therapists for company-sponsored bereavement leave. HR sends a code; the employee gets 6 sessions in 2 weeks with same-day scheduling." },
  { "id": "g018", "industry": "social",         "geo": "Global", "stage": "idea",      "text": "A photo-sharing app where every photo expires after exactly 100 views, total. Forces serendipity and prevents the highlight-reel performance loop of Instagram." },
  { "id": "g019", "industry": "ai_ml",          "geo": "US",     "stage": "mvp",       "text": "A code-review bot that doesn't comment on style — only on architectural drift. Reads your ADRs, your last 6 months of merged PRs, and yells when a new diff contradicts a decision." },
  { "id": "g020", "industry": "sustainability", "geo": "US",     "stage": "idea",      "text": "A residential battery + solar leasing program targeted at California renters — landlord pays nothing, tenant saves 15% on electric, we take 50% of the saving as our spread." },
  { "id": "g021", "industry": "logistics",      "geo": "SE-Asia","stage": "idea",      "text": "A cross-border shipping consolidator for Southeast Asian Shopify sellers selling into the US — drops US shipping cost from $18 to $6 by pooling DHL contracts." },
  { "id": "g022", "industry": "entertainment",  "geo": "US",     "stage": "idea",      "text": "An AI dungeon master service for in-person D&D groups. Pre-game it learns your campaign, mid-game you ask it questions via Bluetooth earbud, it never breaks the table immersion." },
  { "id": "g023", "industry": "fintech",        "geo": "Mexico", "stage": "validated", "text": "A nómina-advance app for Mexican formal-sector workers — earn it Tuesday, get it Tuesday, no interest, employer integrates via API for 1.5% per advance." },
  { "id": "g024", "industry": "healthtech",     "geo": "Canada", "stage": "idea",      "text": "A virtual-first family doctor service for Canadian provinces with 6-month wait lists. Reimbursable in BC/AB/ON. Async + scheduled video. Patients get a real PCP, not a urgent-care cycle." },
  { "id": "g025", "industry": "edtech",         "geo": "US",     "stage": "idea",      "text": "An AI-powered college essay coach that reads admitted-student essays from each target school, then critiques the student's draft against that school's specific aesthetic, not generic 'show don't tell' advice." },
  { "id": "g026", "industry": "saas",           "geo": "US",     "stage": "mvp",       "text": "An end-to-end SOC 2 platform for series-A startups that includes the auditor (in-house, not a marketplace). Subscription includes audit. Half the price of Drata + Prescient combined." },
  { "id": "g027", "industry": "ecommerce",      "geo": "EU",     "stage": "idea",      "text": "A returns-prevention layer for fashion DTC brands — at checkout, AI looks at the buyer's past returns + size profile and blocks them from buying items that have a >40% return probability." },
  { "id": "g028", "industry": "marketplace",    "geo": "US",     "stage": "idea",      "text": "A marketplace of 'dormant founders' (people with one exited or shuttered startup, currently at FAANG) available for 5-hour-a-week advisor roles paid in equity + stipend." },
  { "id": "g029", "industry": "social",         "geo": "US",     "stage": "idea",      "text": "A 'quiet mode' social network where every post auto-deletes if it gets fewer than 10 reactions in 24h. Forces signal over thirst-trap volume." },
  { "id": "g030", "industry": "ai_ml",          "geo": "Global", "stage": "idea",      "text": "An AI video editor that understands narrative — drop in 4 hours of GoPro, it cuts a 90s reel that has actual story arc, not just beat-drop montage." },
  { "id": "g031", "industry": "sustainability", "geo": "US",     "stage": "idea",      "text": "A reusable-cup deposit network for stadiums and concert venues. Vendor sells the drink in a chip-tagged cup; fan gets $2 back at any venue dropbox. We take a margin on the deposit float." },
  { "id": "g032", "industry": "logistics",      "geo": "US",     "stage": "idea",      "text": "A B2B reverse-logistics SaaS for Amazon-FBA sellers — automatically files inventory-loss claims, recovers ~$30K/yr per mid-size seller. We charge 25% of recovered amount." },
  { "id": "g033", "industry": "entertainment",  "geo": "US",     "stage": "idea",      "text": "A 'group-watch' app for live sports — you and your 4 friends each install it, your in-game reactions sync to a shared overlay, audio chats stitch onto a single timestamp track." },
  { "id": "g034", "industry": "fintech",        "geo": "US",     "stage": "validated", "text": "A 401(k) provider for solo founders and 1-employee LLCs — no plan admin, $50/month flat, fund choices curated by Wealthfront-style robo. Replaces $1.2K/yr Guideline tax." },
  { "id": "g035", "industry": "healthtech",     "geo": "US",     "stage": "idea",      "text": "A continuous-glucose-monitor program for non-diabetic high-performers and athletes, with a clinician-reviewed weekly food plan, sold to corporate wellness budgets at $400/employee/month." },
  { "id": "g036", "industry": "edtech",         "geo": "Brazil", "stage": "idea",      "text": "A WhatsApp-based microlearning service that texts Brazilian middle-schoolers a 5-minute math problem each weekday morning, with parent dashboards. R$10/month." },
  { "id": "g037", "industry": "saas",           "geo": "Global", "stage": "validated", "text": "A 'developer-ops' tool for solopreneur SaaS — a single pane that watches your Stripe MRR, GitHub PR queue, error-tracker volume, and reminds you when a metric trends out of band." },
  { "id": "g038", "industry": "ecommerce",      "geo": "US",     "stage": "idea",      "text": "A Shopify-native gift registry replacing Honeyfund/Zola. Couples sync their wedding website + we handle gift fulfillment from any Shopify store on the planet via single checkout." },
  { "id": "g039", "industry": "marketplace",    "geo": "Global", "stage": "idea",      "text": "A marketplace for 'micro-events' — your 8-person dinner party, paid attendees, hosted at a stranger's apartment. Like Airbnb Experiences but with paid hosts and recurring weekly slots." },
  { "id": "g040", "industry": "social",         "geo": "Global", "stage": "idea",      "text": "A 'serious mode' Twitter alternative where the only feed-rank signal is reading-time per post. The longer you read, the more weight your engagement carries. Anti-rage architecture." },
  { "id": "g041", "industry": "ai_ml",          "geo": "Global", "stage": "mvp",       "text": "A platform that lets law firms build their own paralegal LLM by feeding it 5 years of their settled cases. Air-gapped, on-prem, sold by retainer + per-seat license." },
  { "id": "g042", "industry": "sustainability", "geo": "US",     "stage": "idea",      "text": "A consumer EV-charger sharing app — homeowners list their L2 charger after-hours, EV drivers book by the hour. Stripe payouts, Tesla Wall Connector OTA price control." },
  { "id": "g043", "industry": "logistics",      "geo": "US",     "stage": "validated", "text": "A network of micro-warehouses (200 sqft, automated) inside abandoned mall anchor stores, providing same-day fulfillment for mid-size DTC brands without Amazon FBA." },
  { "id": "g044", "industry": "entertainment",  "geo": "Global", "stage": "idea",      "text": "An interactive audiobook platform — at key story decisions the listener says 'go left' or 'go right' aloud, the audio branches in real-time. Authors paid royalty per hour listened." },
  { "id": "g045", "industry": "fintech",        "geo": "US",     "stage": "idea",      "text": "An equity-management tool for early employees — handles 83(b) elections, exercise modeling vs AMT, and secondary-sale facilitation. $99/year per employee, sold to the company." },
  { "id": "g046", "industry": "healthtech",     "geo": "Australia","stage":"idea",     "text": "A primary-care concierge for rural Australian patients (>1hr from a GP) — telehealth, drone-dispatched scripts, monthly subscription. Reimbursable under MBS for chronic-disease cohort." },
  { "id": "g047", "industry": "edtech",         "geo": "Africa", "stage": "idea",      "text": "A vocational-training platform for sub-Saharan Africa pairing youth with European apprenticeship-style remote internships in software, design, and accounting. Paid in USDC." },
  { "id": "g048", "industry": "saas",           "geo": "US",     "stage": "idea",      "text": "An AI sales coach that listens to a salesperson's actual Zoom calls (with consent) and gives them a 90-second, post-call written critique within 5 minutes. Manager dashboard rolls up trends." },
  { "id": "g049", "industry": "ecommerce",      "geo": "Japan",  "stage": "idea",      "text": "A Japanese-aesthetic, calm-design marketplace for handmade household objects, priced in JPY but shipping internationally with consolidated customs. Anti-Amazon visual language." },
  { "id": "g050", "industry": "marketplace",    "geo": "Global", "stage": "idea",      "text": "A marketplace where YC alumni run office hours for sale — $200 for 30 minutes with someone whose company is their stage + industry. Vetted by YC Slack handle. 20% take." }
]
JSON

COUNT=$(python3 -c "import json; print(len(json.load(open('$OUT'))))")
echo "[seed] wrote $COUNT golden ideas to $OUT"
